stages:
  - install_deps
  - lint
  - test
  - build
  - staging
  - production

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - kubernetes-parity-build
  image:                           $CI_IMAGE_TAG

variables:                         &default-vars
  CI_IMAGE:                        "node:16.10"
  DOCKERFILE:                      Dockerfile
  IMAGE_NAME:                      docker.io/paritytech/github-issue-sync
  CI_IMAGE_TAG:                    "node:16.10"
  APP_PORT:                        3000
  # Vault Section
  VAULT_ADDR:                      "https://vault.parity-mgmt-vault.parity.io"
  VAULT_AUTH_PATH:                 "gitlab-parity-io-jwt"
  VAULT_AUTH_ROLE:                 "cicd_gitlab_parity_${CI_PROJECT_NAME}"
  HELM_SECRETS_DRIVER:             vals

.common-refs:                      &common-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs

.test-refs:                        &test-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs

.publish-refs:                     &publish-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/ 

# Run deploy to production only on tag
.production-refs:                  &production-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/ 

.kubernetes-env:                   &kubernetes-env
  image:                           $CI_IMAGE
  tags:
    - kubernetes-parity-build

# fix
.install-deps:
  <<:                              *common-refs
  stage:                           install_deps
  script:
    - yarn
  artifacts:
    name:                          "${CI_JOB_ID}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     1 hour
    paths:
      - ./node_modules
  tags:
    - kubernetes-parity-build

lint:
  stage:                           lint
  <<:                              *kubernetes-env
  <<:                              *common-refs
  script:
    - echo "lint"

test:
  stage:                           test
  <<:                              *kubernetes-env
  <<:                              *common-refs
  script:
    - echo "test"

security-scan:
  stage:                           test
  <<:                              *kubernetes-env
  <<:                              *common-refs
  variables:
    CI_IMAGE:                      "aquasec/trivy:latest"
  script:
    #- trivy fs --exit-code 1 .
    - trivy fs .

# template task for building and pushing an image
.build-push-docker-image:          &build-push-docker-image
  <<:                              *kubernetes-env
  image:                           quay.io/buildah/stable
  script:
    - export VERSION=${CI_COMMIT_SHORT_SHA}
    - test "$Docker_Hub_User_Parity" -a "$Docker_Hub_Pass_Parity" ||
        ( echo "no docker credentials provided"; exit 1 )
    - buildah bud
        --format=docker
        --build-arg VCS_REF="${CI_COMMIT_SHA}"
        --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        --build-arg VERSION="$VERSION"
        --build-arg PORT="$APP_PORT"
        --tag "$IMAGE_NAME:$VERSION"
        --tag "$IMAGE_NAME:latest"
        --file "src/server/$DOCKERFILE" .
    - echo degug $Docker_Hub_User_Parity
    - echo "$Docker_Hub_Pass_Parity" |
        buildah login --username "$Docker_Hub_User_Parity" --password-stdin docker.io
    - buildah info
    - buildah push --format=v2s2 "$IMAGE_NAME:$VERSION"
    - buildah push --format=v2s2 "$IMAGE_NAME:latest"
  after_script:
    - buildah logout --all

build-push:
  stage:                           build
  <<:                              *publish-refs
  <<:                              *build-push-docker-image

# Deploy to Kubernetes
.deploy:                  &deploy-k8s
  script:
    # https://docs.gitlab.com/ee/ci/examples/authenticating-with-hashicorp-vault/#example
    - export VAULT_TOKEN="$(vault write -field=token auth/$VAULT_AUTH_PATH/login role=$VAULT_AUTH_ROLE jwt=$CI_JOB_JWT)"
    - helm dependency update helm/
    - helm secrets upgrade
        --install
        --atomic
        --timeout 300s
        --namespace github-issue-sync
        --values helm/$VALUES_FILE
        --set common.image.tag=latest
        github-issue-sync helm/
 
 #--set common.image.tag="$CI_COMMIT_SHORT_SHA"

deploy-staging:
  variables:
    CI_IMAGE:    "paritytech/kubetools:3.5.3"
    VALUES_FILE: "values-stg.yaml"
  stage:         staging
  environment:
    name:        parity-stg
  <<:            *kubernetes-env
  <<:            *publish-refs
  <<:            *deploy-k8s
  

# FIX ME
.deploy-production:
  variables:
    CI_IMAGE:    "paritytech/kubetools:3.5.3"
    VALUES_FILE: "values-prod.yaml"
  stage:         production
  environment:
    name:        parity-prod
  <<:            *kubernetes-env
  <<:            *production-refs
  <<:            *deploy-k8s
