apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cloudsql.service.name }}
  labels:
    app: {{ .Values.cloudsql.service.name }}
    {{- include "github-issue-sync.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cloudsql.service.port }}
      targetPort: {{ .Values.cloudsql.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "github-issue-sync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.cloudsql.service.name }}
